name: rrc_simulation
channels:
- conda-forge
dependencies:
- python=3.6.9
- numpy==1.19.1
- pinocchio==2.4.7
- pip==20.1.1
- pip:
  - pybullet==2.8.4
  - gym==0.17.2
  - opencv-python==4.2.0.34
  - catkin-pkg==0.4.22
  # the below packages are needed for stable-baselines
  - tensorflow==1.15.0
  - pandas==0.24.2
  - joblib==0.16.0
  - stable-baselines==2.10.0
  
